myapp/urls.py
from django.urls import path

from . import views

app_name = "myapp"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote", views.vote, name="vote"),
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path("", views.index, name ='index'),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include("myapp.urls")),
    path("", include("pages.urls")),
]

myapp/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

pages/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
 
from .models import Question, Choice
 
 
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'myapp/index.html', context)
 
 
def detail(request, question_id):
    try:
        question = Question.objects.get(pk = question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'myapp/detail.html', {'question': question})
 
 
def results(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'myapp/results.html', {'question': question})

 
def vote(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'myapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('myapp:results', args =(question.id, )))

pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "pages/index.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
 
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>PollPulse {% block title %}{% endblock %}</title>
</head>
 
<body>
    {% include 'partials/_navbar.html'%}
    <div class="container">
        <div class="row">
            <div class=".col-md-6 m-auto">
                {% block content %}{% endblock%}
            </div>
        </div>
    </div>
</body>
 
</html>

templates/myapp/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" style="box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);" href="{% url 'myapp:index' %}">Back To Polls</a>

<h1 class="text-center mb-3" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">
    {{ question.question_text }}
</h1>

{% if error_message %}
<p class="alert alert-danger" style="box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'myapp:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <div class="form-check" style="box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); background-color: white;">
        <input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
            value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" style="box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);" />
</form>


<style>
    body {
    margin: auto;
    font-family: -apple-system, BlinkMacSystemFont, sans-serif;
    overflow: auto;
    background: linear-gradient(315deg, rgba(101,0,94,1) 3%, rgba(60,132,206,1) 38%, rgba(48,238,226,1) 68%, rgba(255,25,25,1) 98%);
    animation: gradient 15s ease infinite;
    background-size: 400% 400%;
    background-attachment: fixed;
}

@keyframes gradient {
    0% {
        background-position: 0% 0%;
    }
    50% {
        background-position: 100% 100%;
    }
    100% {
        background-position: 0% 0%;
    }
}

.wave {
    background: rgb(255 255 255 / 25%);
    border-radius: 1000% 1000% 0 0;
    position: fixed;
    width: 200%;
    height: 12em;
    animation: wave 10s -3s linear infinite;
    transform: translate3d(0, 0, 0);
    opacity: 0.8;
    bottom: 0;
    left: 0;
    z-index: -1;
}

.wave:nth-of-type(2) {
    bottom: -1.25em;
    animation: wave 18s linear reverse infinite;
    opacity: 0.8;
}

.wave:nth-of-type(3) {
    bottom: -2.5em;
    animation: wave 20s -1s reverse infinite;
    opacity: 0.9;
}

@keyframes wave {
    2% {
        transform: translateX(1);
    }

    25% {
        transform: translateX(-25%);
    }

    50% {
        transform: translateX(-50%);
    }

    75% {
        transform: translateX(-25%);
    }

    100% {
        transform: translateX(1);
    }
}
.card {
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        transition: transform 0.5s ease;
    }

    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
    }

    .card-body {
        transform-style: preserve-3d;
    }

    .card-body:hover {
        transform: rotateY(10deg);
    }
</style>
{% endblock %}

templates/myapp/index.html
{% extends 'base.html' %}
{% block content %}
<div>
    <div>
    <div class="wave">
        <div class="wave">
            <div class="wave">
            </div>
        </div>
    </div>
</div>
<h1 class="text-center mb-3" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">Poll Questions</h1>
{% if latest_question_list %}
{% for question in latest_question_list %}
<div class="card text-center" style="width: 400px; margin: 50px auto;">
    <div class="card-body">
        <p class="lead">{{ question.question_text }}</p>
        <a href="{% url 'myapp:detail' question.id %}" class="btn btn-dark">Vote Now</a>
        <a href="{% url 'myapp:results' question.id %}" class="btn btn-dark">Results</a>
    </div>
</div>
{% endfor %}
{% else %}
<p>No polls available</p>
{% endif %}

<style>
    body {
    margin: auto;
    font-family: -apple-system, BlinkMacSystemFont, sans-serif;
    overflow: auto;
    background: linear-gradient(315deg, rgba(101,0,94,1) 3%, rgba(60,132,206,1) 38%, rgba(48,238,226,1) 68%, rgba(255,25,25,1) 98%);
    animation: gradient 15s ease infinite;
    background-size: 400% 400%;
    background-attachment: fixed;
}

@keyframes gradient {
    0% {
        background-position: 0% 0%;
    }
    50% {
        background-position: 100% 100%;
    }
    100% {
        background-position: 0% 0%;
    }
}

.wave {
    background: rgb(255 255 255 / 25%);
    border-radius: 1000% 1000% 0 0;
    position: fixed;
    width: 200%;
    height: 12em;
    animation: wave 10s -3s linear infinite;
    transform: translate3d(0, 0, 0);
    opacity: 0.8;
    bottom: 0;
    left: 0;
    z-index: -1;
}

.wave:nth-of-type(2) {
    bottom: -1.25em;
    animation: wave 18s linear reverse infinite;
    opacity: 0.8;
}

.wave:nth-of-type(3) {
    bottom: -2.5em;
    animation: wave 20s -1s reverse infinite;
    opacity: 0.9;
}

@keyframes wave {
    2% {
        transform: translateX(1);
    }

    25% {
        transform: translateX(-25%);
    }

    50% {
        transform: translateX(-50%);
    }

    75% {
        transform: translateX(-25%);
    }

    100% {
        transform: translateX(1);
    }
}
.card {
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        transition: transform 0.5s ease;
    }

    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
    }

    .card-body {
        transform-style: preserve-3d;
    }

    .card-body:hover {
        transform: rotateY(10deg);
    }
</style>
{% endblock %}

templates/myapp/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">
    {{ question.question_text }}
</h1>

<ul class="list-group mb-5">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item" style="box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">
        {{ choice.choice_text }} 
        <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul>

<a class="btn btn-secondary" style="box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);" href="{% url 'myapp:index' %}">Back To Polls</a>
<a class="btn btn-dark" style="box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);" href="{% url 'myapp:detail' question.id %}">Vote again?</a>


<style>
    body {
    margin: auto;
    font-family: -apple-system, BlinkMacSystemFont, sans-serif;
    overflow: auto;
    background: linear-gradient(315deg, rgba(101,0,94,1) 3%, rgba(60,132,206,1) 38%, rgba(48,238,226,1) 68%, rgba(255,25,25,1) 98%);
    animation: gradient 15s ease infinite;
    background-size: 400% 400%;
    background-attachment: fixed;
}

@keyframes gradient {
    0% {
        background-position: 0% 0%;
    }
    50% {
        background-position: 100% 100%;
    }
    100% {
        background-position: 0% 0%;
    }
}

.wave {
    background: rgb(255 255 255 / 25%);
    border-radius: 1000% 1000% 0 0;
    position: fixed;
    width: 200%;
    height: 12em;
    animation: wave 10s -3s linear infinite;
    transform: translate3d(0, 0, 0);
    opacity: 0.8;
    bottom: 0;
    left: 0;
    z-index: -1;
}

.wave:nth-of-type(2) {
    bottom: -1.25em;
    animation: wave 18s linear reverse infinite;
    opacity: 0.8;
}

.wave:nth-of-type(3) {
    bottom: -2.5em;
    animation: wave 20s -1s reverse infinite;
    opacity: 0.9;
}

@keyframes wave {
    2% {
        transform: translateX(1);
    }

    25% {
        transform: translateX(-25%);
    }

    50% {
        transform: translateX(-50%);
    }

    75% {
        transform: translateX(-25%);
    }

    100% {
        transform: translateX(1);
    }
}
.card {
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        transition: transform 0.5s ease;
    }

    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
    }

    .card-body {
        transform-style: preserve-3d;
    }

    .card-body:hover {
        transform: rotateY(10deg);
    }
</style>
{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}
 
<div>
    <div>
    <div class="wave">
        <div class="wave">
            <div class="wave">
            </div>
        </div>
    </div>
</div>
<div class="card text-center" style="width: 400px; margin: 50px auto;">
    <div class="card-body">
        <h1>Welcome To PollPulse!</h1>
        <p>This is an Polling Web Application built with Django</p>
        <a class="btn btn-dark" href="{% url 'myapp:index' %}">
            View Available Polls</a>
    </div>
</div>
</div>
            

<style>
    body {
    margin: auto;
    font-family: -apple-system, BlinkMacSystemFont, sans-serif;
    overflow: auto;
    background: linear-gradient(315deg, rgba(101,0,94,1) 3%, rgba(60,132,206,1) 38%, rgba(48,238,226,1) 68%, rgba(255,25,25,1) 98%);
    animation: gradient 15s ease infinite;
    background-size: 400% 400%;
    background-attachment: fixed;
}

@keyframes gradient {
    0% {
        background-position: 0% 0%;
    }
    50% {
        background-position: 100% 100%;
    }
    100% {
        background-position: 0% 0%;
    }
}

.wave {
    background: rgb(255 255 255 / 25%);
    border-radius: 1000% 1000% 0 0;
    position: fixed;
    width: 200%;
    height: 12em;
    animation: wave 10s -3s linear infinite;
    transform: translate3d(0, 0, 0);
    opacity: 0.8;
    bottom: 0;
    left: 0;
    z-index: -1;
}

.wave:nth-of-type(2) {
    bottom: -1.25em;
    animation: wave 18s linear reverse infinite;
    opacity: 0.8;
}

.wave:nth-of-type(3) {
    bottom: -2.5em;
    animation: wave 20s -1s reverse infinite;
    opacity: 0.9;
}

@keyframes wave {
    2% {
        transform: translateX(1);
    }

    25% {
        transform: translateX(-25%);
    }

    50% {
        transform: translateX(-50%);
    }

    75% {
        transform: translateX(-25%);
    }

    100% {
        transform: translateX(1);
    }
}
.card {
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        transition: transform 0.5s ease;
    }

    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
    }

    .card-body {
        transform-style: preserve-3d;
    }

    .card-body:hover {
        transform: rotateY(10deg);
    }
</style>
{% endblock %}

templates/partials/_navbar.html
<div>
    <nav class="navbar navbar-dark bg-black mb-4">
        <div class="container">
            <a class="navbar-brand" href="/">PollPulse</a>
            <button class="btn btn-primary btn-3d" onclick="logout()">Logout</button>
        </div>
    </nav>
</div>

<style>
    .navbar {
    background-color: rgb(29, 25, 25);
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
}

.btn-3d {
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 5px;
    padding: 10px 20px;
    cursor: pointer;
    transition: transform 0.3s, box-shadow 0.3s;
}

.btn-3d:hover {
    transform: translateY(-3px);
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
}


</style>